#!/bin/bash

POSIXLY_CORRECT=yes

usage() {
    echo "Useage: corona [-h] [FILTERS] [COMMAND] [LOG [LOG2 [...]]"
}

while getopts :a:b:g:hs opt;
do  case "$opt" in
        a)  echo "Option 'a' found with parameter '$OPTARG'.";;
        b)  echo "Option 'b' found with parameter '$OPTARG'.";;
        g)  echo "Option 'g' found with parameter '$OPTARG'.";;
        h)  usage;;
        s)  echo "Option 's'.";;
        *)  usage >&2
            exit 1;;
    esac
done

((OPTIND--))
shift $OPTIND

case "$*" in
    infected)  echo "Option 'infected' found.";;
    merge)  echo "Option 'merge' found.";;
    gender)  echo "Option 'gender' found.";;
    age)  echo "Option 'age' found.";;
    daily)  echo "Option 'daily' found.";;
    monthly)  echo "Option 'monthly' found.";;
    yearly)  echo "Option 'yearly' found.";;
    countries)  echo "Option 'countries' found.";;
    districts)  echo "Option 'districts' found.";;
    regions)  echo "Option 'regions' found.";;
    "") echo "No more arguments.";;
    *) usage;;
esac